openapi: 3.0.1
info:
  title: mq-connector
  version: v0
servers:
  - url: http://mq-connector-git.apps:8080
    description: Generated server url
paths:
  /:
    post:
      tags:
        - user-info-controller
      operationId: createLeadInSalesforce
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfo'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: string
components:
  schemas:
    UserInfo:
      type: object
      properties:
        id:
          type: string
        fname:
          type: string
        lname:
          type: string
        email:
          type: string
        phone:
          type: string
        company:
          type: string
        comments:
          type: string
